// Code generated by go-swagger; DO NOT EDIT.

package comment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CommentHandlerFunc turns a function with the right signature into a comment handler
type CommentHandlerFunc func(CommentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CommentHandlerFunc) Handle(params CommentParams) middleware.Responder {
	return fn(params)
}

// CommentHandler interface for that can handle valid comment params
type CommentHandler interface {
	Handle(CommentParams) middleware.Responder
}

// NewComment creates a new http.Handler for the comment operation
func NewComment(ctx *middleware.Context, handler CommentHandler) *Comment {
	return &Comment{Context: ctx, Handler: handler}
}

/*Comment swagger:route GET /comment comment comment

写了一句评论

*/
type Comment struct {
	Context *middleware.Context
	Handler CommentHandler
}

func (o *Comment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCommentParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
