// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi hatlonely.me
不想依赖第三方的统计和评论，自己开发一个点赞评论系统


    Schemes:
      http
    Host: hatlonely.com
    BasePath: /api
    Version: 1.0.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: <hatlonely@foxmail.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
