// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "不想依赖第三方的统计和评论，自己开发一个点赞评论系统",
    "title": "hatlonely.me",
    "contact": {
      "email": "hatlonely@foxmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "host": "hatlonely.com",
  "basePath": "/api",
  "paths": {
    "/comment": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "comment"
        ],
        "summary": "写了一句评论",
        "operationId": "comment",
        "parameters": [
          {
            "type": "string",
            "description": "文章标题",
            "name": "title",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "description": "文章评论",
            "name": "comment",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "description": "昵称",
            "name": "nickname",
            "in": "query"
          },
          {
            "type": "string",
            "description": "邮箱地址",
            "name": "mail",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "成功",
            "schema": {
              "$ref": "#/definitions/OkModel"
            }
          },
          "400": {
            "description": "失败",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      }
    },
    "/like": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "like"
        ],
        "summary": "点了一个赞",
        "operationId": "like",
        "parameters": [
          {
            "type": "string",
            "description": "文章标题",
            "name": "title",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "成功",
            "schema": {
              "$ref": "#/definitions/OkModel"
            }
          },
          "400": {
            "description": "失败",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ErrorModel": {
      "type": "object",
      "required": [
        "message",
        "code"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "default": 400,
          "enum": [
            400
          ]
        },
        "message": {
          "type": "string",
          "default": "error"
        }
      }
    },
    "OkModel": {
      "type": "object",
      "required": [
        "message",
        "code"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "default": 200,
          "enum": [
            200
          ]
        },
        "message": {
          "type": "string",
          "default": "ok",
          "enum": [
            "ok"
          ]
        }
      }
    }
  },
  "tags": [
    {
      "description": "点赞",
      "name": "like"
    },
    {
      "description": "评论",
      "name": "comment"
    }
  ]
}`))
}
